# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing dependencies
          command: |
            mkdir ~/.kube
            echo ${KUBECONFIG_ENCODED} | base64 -d > ~/.kube/config
            apk add --no-cache curl
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: Building docker image
          command: docker build -t grantbachman/sample-app:${CIRCLE_SHA1} .
      - run:
          name: Running tests
          command: docker run grantbachman/sample-app:${CIRCLE_SHA1} python setup.py test
      - run:
          name: Pushing docker image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push grantbachman/sample-app:${CIRCLE_SHA1}


